#!/bin/bash

# GitHub Pages 배포 가이드
# 이 스크립트는 직접 실행하지 마세요. 아래 명령어를 참고용으로 사용하세요.

echo "==================================="
echo "GitHub Pages 배포 가이드"
echo "==================================="
echo ""
echo "1. GitHub에서 새 저장소 생성"
echo "   - 저장소명: focus-timer (또는 원하는 이름)"
echo "   - Public으로 생성"
echo ""
echo "2. 로컬에서 Git 초기화 및 푸시"
echo "   cd focus-timer"
echo "   git init"
echo "   git add ."
echo '   git commit -m "Initial commit: Focus Timer"'
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR-USERNAME/focus-timer.git"
echo "   git push -u origin main"
echo ""
echo "3. GitHub Pages 활성화"
echo "   - GitHub 저장소 페이지로 이동"
echo "   - Settings > Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main / (root)"
echo "   - Save 클릭"
echo ""
echo "4. 5분 후 다음 주소로 접속"
echo "   https://YOUR-USERNAME.github.io/focus-timer/"
echo ""
echo "5. Buy Me a Coffee 설정"
echo "   - https://www.buymeacoffee.com/ 가입"
echo "   - index.html에서 링크 수정"
echo ""
echo "==================================="
echo "배포 완료 후 할 일"
echo "==================================="
echo ""
echo "✅ 커뮤니티 공유 (에브리타임, 블라인드 등)"
echo "✅ SNS 홍보 (#공부타이머 #집중력)"
echo "✅ Google Search Console 등록"
echo "✅ Google Analytics 연동 (선택)"
echo ""
